#!/usr/bin/env bash

CWD=$(pwd | sed 's/\//\n/g' | tail -n 1)

if [ $CWD == "scripts" ]
then
	cd ..
fi

TAG=ghcr.io/darthmikke/wsgi:$(git log -n 1 --format="%h")

docker build -t $TAG src
echo "Built $TAG"
